language: generic
dist: xenial
sudo: required
install:
  - sudo apt-get update
  - sudo apt-get install -y unzip
  - wget -q -P /tmp https://releases.hashicorp.com/packer/1.3.1/packer_1.3.1_linux_amd64.zip
  - sudo unzip -o /tmp/packer_1.3.1_linux_amd64.zip -d /usr/local/bin/
script:
  - packer validate template.json
